### ISSUE TITLE
FR: Support table alignment cookies

### ISSUE THREAD

**Issue by pank** [emacsorphanage/ox-pandoc#3]
Hi there,

Alignment cookies for tables do not seem to work when exporting to at least `docx`. I don't know if this is a limitation of pandoc or ox-pandoc.

Example:
```org
#+caption: left, center and right aligned columns 
| <l>    |   <c>    |      <r> |
| a      |    b     |        c |
| aaaaaa | bbbbbbbb | cccccccc |
```

The columns should have differently aligned columns, but `ox-pandoc` exports all of them as left-aligned. 

Thanks,
Rasmus

PS: I first posted this to the old repo; I didn't see one could also add new issues here. Sometimes it's not possible to add new issues to forked projects on github...

**Comment by a-fent** [comment]
Thanks for the report. This is a bug in `ox-pandoc` because both Org mode and pandoc used directly do support this syntax for e.g. ODT and HTML (I couldn't test docx just now).

The column alignment information gets swallowed in the intermediate conversion to org. It'll require a custom `org-pandoc-export-table` function modelled on `org-html-table` in org.

**Comment by a-fent** [comment]
See: https://list.orgmode.org/874jy7nyxv.fsf@localhost/T/#t

**Comment by a-fent** [comment]
Good news - this should be fixed by changes in Org Mode: https://list.orgmode.org/874jy7nyxv.fsf@localhost/

Test and verify when next Org Mode version is released.

**Comment by a-fent** [comment]
The column alignment is now correctly exported to ODT when used with Org Mode 9.7.
